title: My Professional Experience
author: VMistry90
email: vishulmistry15@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is for showing the list of skills I have and referencing the various projects worked on that I have 
  included in github via Visual Studios.

# social links
github_username:  VMistry90

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
